const HARDCODED_GROUPS = [
  {
    id: "1",
    name: "Sunset Plaza",
    owner_id: "owner_123",
    city: "San Francisco",
    address: "123 Sunset Blvd",
    local_currency: "usd",
    zipcode: "94101",
    price_kwh: 0.12,
  },
  {
    id: "2",
    name: "Green Acres",
    owner_id: "owner_234",
    city: "Los Angeles",
    address: "456 Green St",
    local_currency: "usd",
    zipcode: "90001",
    price_kwh: 0.15,
  },
  {
    id: "3",
    name: "River Park",
    owner_id: "owner_345",
    city: "Chicago",
    address: "789 River Rd",
    local_currency: "usd",
    zipcode: "60601",
    price_kwh: 0.1,
  },
  {
    id: "4",
    name: "Mountain View",
    owner_id: "owner_456",
    city: "Denver",
    address: "101 Mountain Dr",
    local_currency: "usd",
    zipcode: "80201",
    price_kwh: 0.11,
  },
  {
    id: "5",
    name: "Ocean Breeze",
    owner_id: "owner_567",
    city: "Miami",
    address: "202 Ocean Ave",
    local_currency: "usd",
    zipcode: "33101",
    price_kwh: 0.14,
  },
  {
    id: "6",
    name: "Pine Hills",
    owner_id: "owner_678",
    city: "Seattle",
    address: "303 Pine St",
    local_currency: "usd",
    zipcode: "98101",
    price_kwh: 0.13,
  },
  {
    id: "7",
    name: "Lakeside",
    owner_id: "owner_789",
    city: "Minneapolis",
    address: "404 Lake Blvd",
    local_currency: "usd",
    zipcode: "55401",
    price_kwh: 0.09,
  },
  {
    id: "8",
    name: "Desert Oasis",
    owner_id: "owner_890",
    city: "Phoenix",
    address: "505 Desert Rd",
    local_currency: "usd",
    zipcode: "85001",
    price_kwh: 0.16,
  },
  {
    id: "9",
    name: "Urban Heights",
    owner_id: "owner_901",
    city: "New York",
    address: "606 Urban Ln",
    local_currency: "usd",
    zipcode: "10001",
    price_kwh: 0.17,
  },
  {
    id: "10",
    name: "Countryside",
    owner_id: "owner_012",
    city: "Austin",
    address: "707 Country Rd",
    local_currency: "usd",
    zipcode: "73301",
    price_kwh: 0.08,
  },
];

export default HARDCODED_GROUPS;
